github:
  enabled_merge_buttons:
    squash: true
    squash_commit_message: PR_TITLE_AND_DESC
    merge: false
    rebase: false
  features:
    issues: true
  pull_requests:
    allow_update_branch: true
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
